### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by varkor** [varkor/quiver#22]
I'd like to push for a "version 1.0" and make an announcement post and advertise quiver on various media once I think that it's ready. I'll use this issue to track what should happen as part of this push.

**Implementation**
- [x] Move to dedicated domain.
- [x] No JavaScript support.
- [x] Custom `.sty`.
- [x] Add a version number.
- [x] Open Graph protocol support.
- [x] Test in Chrome, Safari, Firefox.

**Publicity**
- [x] Update `README.md`, with representative screenshots and diagrams.
- [x] Edit GitHub about section.
- [x] Write an announcement blog post.
- [x] Make posts on Reddit, Twitter, Category Theory Zulip, etc.
- [x] Link [Twitter account](https://twitter.com/q_uiver_app), etc.
- [x] Add to the https://github.com/xiaohanyu/awesome-tikz list (cc https://github.com/varkor/quiver/issues/15).
- [x] Share on https://mathoverflow.net/questions/365387/time-saving-technology-tricks-for-writing-papers.
- [ ] Suggest possibility of quiver as a KateX extension for commutative diagrams (cf. https://github.com/KaTeX/KaTeX/issues/219 and https://github.com/KaTeX/KaTeX/issues/1834).

Other suggestions are welcome.

**Comment by varkor** [comment]
The beta is now available at https://q.uiver.app/dev/.
